package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	LIST_ITEM_BACKUP, LIST_ITEM_INDEX,
	SEARCH_LOOKUP, SEARCH_LOOKUP_REPLY,
	AD_FETCH, AD_FETCH_REPLY,
	SUBSCRIBE_REQUEST, MARKET_NOTIFICATION,
	// Buy mutex (Suzuki-Kasami) + execution + backup sync.
	BUY_OWNER_LOOKUP, BUY_OWNER_REPLY,
	MUTEX_REQUEST, MUTEX_TOKEN,
	BUY_EXEC, BUY_EXEC_REPLY,
	BACKUP_QTY_UPDATE
}
